// <auto-generated />
using System;
using CommonService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009142859_CapacityReservation")]
    partial class CapacityReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonService.Domain.Entities.AdminAccount", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("admin_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<byte>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ADMIN", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("actor_type");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("changed_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("LogId");

                    b.HasIndex("AdminId");

                    b.ToTable("ADMIN_AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.BookingSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TIME(0)")
                        .HasColumnName("end_time");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("shift_code");

                    b.Property<string>("SkillTags")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("skill_tags");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("DATE")
                        .HasColumnName("slot_date");

                    b.Property<string>("SlotSource")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("slot_source");

                    b.Property<string>("SlotStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("slot_status");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TIME(0)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("SlotId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("WorkerId", "SlotDate", "ShiftCode")
                        .IsUnique();

                    b.ToTable("BOOKING_SLOT", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CapacityReservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("SlotId");

                    b.ToTable("CapacityReservations");
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CheckInLog", b =>
                {
                    b.Property<long>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("checkin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CheckinId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<byte>("CallAttempts")
                        .HasColumnType("TINYINT")
                        .HasColumnName("call_attempts");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTime?>("CustomerAbsentAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("customer_absent_at");

                    b.Property<decimal>("DeviceLat")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("device_lat");

                    b.Property<decimal>("DeviceLng")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("device_lng");

                    b.Property<decimal>("DistanceM")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(7,2)")
                        .HasColumnName("distance_m");

                    b.Property<string>("FallbackMethod")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fallback_method");

                    b.Property<string>("FallbackPhotoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fallback_photo_url");

                    b.Property<bool>("GpsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("gps_verified");

                    b.HasKey("CheckinId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("CHECK_IN_LOG", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("account_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("TrustScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(3,2)")
                        .HasColumnName("trust_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CustomerAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address_line");

                    b.Property<byte?>("Bathrooms")
                        .HasColumnType("TINYINT")
                        .HasColumnName("bathrooms");

                    b.Property<byte?>("Bedrooms")
                        .HasColumnType("TINYINT")
                        .HasColumnName("bedrooms");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("district");

                    b.Property<decimal>("FloorAreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("floor_area_m2");

                    b.Property<string>("HousingType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("housing_type");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("label");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("longitude");

                    b.Property<byte>("NumFloors")
                        .HasColumnType("TINYINT")
                        .HasColumnName("num_floors");

                    b.Property<decimal>("TotalAreaM2")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("total_area_m2")
                        .HasComputedColumnSql("[floor_area_m2] * [num_floors]", true);

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CUSTOMER_ADDRESS", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.DisputeTicket", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dispute_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisputeId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("category");

                    b.Property<decimal?>("CompensationAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("compensation_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisputeStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("dispute_status");

                    b.Property<string>("EvidenceUrls")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidence_urls");

                    b.Property<string>("FaultParty")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("fault_party");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("raised_by");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int")
                        .HasColumnName("resolved_by");

                    b.Property<DateTime>("SlaDueAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("sla_due_at");

                    b.HasKey("DisputeId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ResolvedBy");

                    b.ToTable("DISPUTE_TICKET", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.EscrowTransaction", b =>
                {
                    b.Property<long>("EscrowTxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("escrow_txn_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EscrowTxnId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_admin_id");

                    b.Property<int?>("DisputeId")
                        .HasColumnType("int")
                        .HasColumnName("dispute_id");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<decimal?>("SlaPointsDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("sla_points_delta");

                    b.Property<string>("TxnType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("txn_type");

                    b.HasKey("EscrowTxnId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("DisputeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentId");

                    b.ToTable("ESCROW_TRANSACTION", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.FavoriteWorker", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.HasKey("CustomerId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("FAVORITE_WORKER", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.IncidentLog", b =>
                {
                    b.Property<long>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncidentId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("incident_type");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("longitude");

                    b.Property<bool>("PenaltyWaived")
                        .HasColumnType("bit")
                        .HasColumnName("penalty_waived");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("RedispatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("redispatch_status");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("reported_at");

                    b.HasKey("IncidentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("INCIDENT_LOG", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<decimal?>("AbsenceFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("absence_fee_amount");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("accepted_at");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<byte>("AssignmentSeq")
                        .HasColumnType("TINYINT")
                        .HasColumnName("assignment_seq");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("assignment_status");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(4,3)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CustomerConfirmedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("customer_confirmed_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<byte>("DispatchRadiusKm")
                        .HasColumnType("TINYINT")
                        .HasColumnName("dispatch_radius_km");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal?>("MatchingScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("matching_score");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PayoutAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("payout_amount");

                    b.Property<int?>("PayoutItemId")
                        .HasColumnType("int")
                        .HasColumnName("payout_item_id");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("service_tier");

                    b.Property<int>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkZone")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("work_zone");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PayoutItemId");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasFilter("[assignment_status] <> 'CANCELLED' AND [assignment_status] <> 'CANCELLED_BY_WORKER' AND [assignment_status] <> 'REASSIGNED'");

                    b.HasIndex("WorkerId");

                    b.ToTable("JOB_ASSIGNMENT", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobOrder", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<decimal>("AreaSnapshotM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("area_snapshot_m2");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("customer_note");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("order_code");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("order_status");

                    b.Property<string>("RequiredSkill")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("required_skill");

                    b.Property<byte>("RequiredWorkers")
                        .HasColumnType("TINYINT")
                        .HasColumnName("required_workers");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("DATE")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("service_tier");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("shift_code");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("JOB_ORDER", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobOrderExtension", b =>
                {
                    b.Property<int>("ExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("extension_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtensionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("decided_at");

                    b.Property<string>("ExtStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ext_status");

                    b.Property<decimal>("ExtraAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("extra_amount");

                    b.Property<decimal>("ExtraHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(3,1)")
                        .HasColumnName("extra_hours");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("requested_at");

                    b.Property<string>("WorkerDecision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("worker_decision");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("ExtensionId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.ToTable("JOB_ORDER_EXTENSION", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobPhoto", b =>
                {
                    b.Property<long>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("photo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PhotoId"));

                    b.Property<byte>("AngleNo")
                        .HasColumnType("TINYINT")
                        .HasColumnName("angle_no");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("captured_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("is_accepted");

                    b.Property<string>("PhotoPhase")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("photo_phase");

                    b.Property<double>("VolScore")
                        .HasColumnType("FLOAT")
                        .HasColumnName("vol_score");

                    b.HasKey("PhotoId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("JOB_PHOTO", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.OtpCode", b =>
                {
                    b.Property<long>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OtpId"));

                    b.Property<byte>("AttemptCount")
                        .HasColumnType("TINYINT")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RequestedIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("requested_ip");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("role");

                    b.HasKey("OtpId");

                    b.HasIndex("RequestedIp", "CreatedAt");

                    b.HasIndex("PhoneNumber", "Role", "CreatedAt");

                    b.ToTable("OTP_CODE", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PartnerAgency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("AgencyStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("agency_status");

                    b.Property<string>("BankAccountNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("bank_account_no");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EscrowDepositBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("escrow_deposit_balance");

                    b.Property<byte>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("GuaranteeFileUrl")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("guarantee_file_url");

                    b.Property<DateTime?>("GuaranteeSignedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("guarantee_signed_at");

                    b.Property<bool>("IsVerifiedPartner")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified_partner");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LegalRepresentative")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("legal_representative");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<decimal>("SlaScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("sla_score");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("tax_code");

                    b.Property<int>("WorkerQuota")
                        .HasColumnType("int")
                        .HasColumnName("worker_quota");

                    b.HasKey("AgencyId");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("PARTNER_AGENCY", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PartnerSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit")
                        .HasColumnName("auto_renew");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("end_date");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("start_date");

                    b.Property<string>("SubStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sub_status");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("PackageId");

                    b.ToTable("PARTNER_SUBSCRIPTION", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExtensionId")
                        .HasColumnType("int")
                        .HasColumnName("extension_id");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayTxnRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("gateway_txn_ref");

                    b.Property<string>("IpnPayload")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ipn_payload");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("paid_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("purpose");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("qr_payload");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TxnStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("txn_status");

                    b.HasKey("PaymentId");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("GatewayTxnRef")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PAYMENT_TRANSACTION", null, t =>
                        {
                            t.HasCheckConstraint("CK_PAYMENT_TRANSACTION_purpose", "([purpose] = 'ORDER' AND [order_id] IS NOT NULL AND [extension_id] IS NULL AND [subscription_id] IS NULL) OR ([purpose] = 'EXTENSION' AND [order_id] IS NULL AND [extension_id] IS NOT NULL AND [subscription_id] IS NULL) OR ([purpose] = 'SUBSCRIPTION' AND [order_id] IS NULL AND [extension_id] IS NULL AND [subscription_id] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PayoutBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("batch_status");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("confirmed_at");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("ExportFileUrl")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("export_file_url");

                    b.Property<string>("PeriodMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .HasColumnName("period_month")
                        .IsFixedLength();

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("BatchId");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("PeriodMonth")
                        .IsUnique();

                    b.ToTable("PAYOUT_BATCH", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PayoutItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<string>("BankAccountNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("bank_account_no");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<string>("ItemStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("item_status");

                    b.Property<int>("JobCount")
                        .HasColumnType("int")
                        .HasColumnName("job_count");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<string>("PayeeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payee_type");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<DateTime?>("TransferredAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("transferred_at");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("ItemId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("BatchId");

                    b.HasIndex("WorkerId");

                    b.ToTable("PAYOUT_ITEM", null, t =>
                        {
                            t.HasCheckConstraint("CK_PAYOUT_ITEM_payee", "([payee_type] = 'FREELANCER' AND [worker_id] IS NOT NULL AND [agency_id] IS NULL) OR ([payee_type] = 'AGENCY' AND [worker_id] IS NULL AND [agency_id] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PriceRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("AreaBracket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("area_bracket");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("service_tier");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("RuleId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("ServiceTier", "AreaBracket")
                        .IsUnique();

                    b.ToTable("PRICE_RULE", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refresh_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("family_id");

                    b.Property<long?>("ReplacedById")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("revoked_at");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("subject_role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ReplacedById");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("skill_code");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillCode")
                        .IsUnique();

                    b.ToTable("SKILL", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("billing_cycle");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(4,3)")
                        .HasColumnName("commission_rate");

                    b.Property<bool>("HasAnalytics")
                        .HasColumnType("bit")
                        .HasColumnName("has_analytics");

                    b.Property<bool>("HasRosterDashboard")
                        .HasColumnType("bit")
                        .HasColumnName("has_roster_dashboard");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("package_code");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("package_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("price");

                    b.Property<bool>("PriorityDispatch")
                        .HasColumnType("bit")
                        .HasColumnName("priority_dispatch");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("tier");

                    b.Property<int>("WorkerQuota")
                        .HasColumnType("int")
                        .HasColumnName("worker_quota");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageCode")
                        .IsUnique();

                    b.ToTable("SUBSCRIPTION_PACKAGE", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.TwoWayRating", b =>
                {
                    b.Property<long>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RatingId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaJson")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("criteria_json");

                    b.Property<string>("RaterRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rater_role");

                    b.Property<byte>("Stars")
                        .HasColumnType("TINYINT")
                        .HasColumnName("stars");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("RatingId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("AssignmentId", "RaterRole")
                        .IsUnique();

                    b.ToTable("TWO_WAY_RATING", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("bank_account_no");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_name");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("int")
                        .HasColumnName("completed_jobs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentLat")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("current_lat");

                    b.Property<decimal?>("CurrentLng")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("current_lng");

                    b.Property<decimal?>("EkycConfidence")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("ekyc_confidence");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsSuperFreelancer")
                        .HasColumnType("bit")
                        .HasColumnName("is_super_freelancer");

                    b.Property<int?>("KycReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("kyc_reviewed_by");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kyc_status");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("national_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("RatingAvg")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(3,2)")
                        .HasColumnName("rating_avg");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("work_status");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("worker_type");

                    b.HasKey("WorkerId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("KycReviewedBy");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("WORKER", null, t =>
                        {
                            t.HasCheckConstraint("CK_WORKER_type_agency", "([worker_type] = 'FREELANCER' AND [agency_id] IS NULL) OR ([worker_type] = 'AGENCY_STAFF' AND [agency_id] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CommonService.Domain.Entities.WorkerSkill", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(3,1)")
                        .HasColumnName("years_of_experience");

                    b.HasKey("WorkerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("WORKER_SKILL", (string)null);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.BookingSlot", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CapacityReservation", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.BookingSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CheckInLog", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.CustomerAddress", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.DisputeTicket", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.EscrowTransaction", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CommonService.Domain.Entities.DisputeTicket", null)
                        .WithMany()
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CommonService.Domain.Entities.JobOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CommonService.Domain.Entities.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.FavoriteWorker", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.IncidentLog", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobAssignment", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommonService.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.JobOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.PayoutItem", null)
                        .WithMany()
                        .HasForeignKey("PayoutItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CommonService.Domain.Entities.BookingSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobOrder", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.CustomerAddress", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobOrderExtension", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.JobPhoto", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PartnerSubscription", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.SubscriptionPackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobOrderExtension", null)
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CommonService.Domain.Entities.JobOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CommonService.Domain.Entities.PartnerSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PayoutBatch", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PayoutItem", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommonService.Domain.Entities.PayoutBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.PriceRule", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.TwoWayRating", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.JobAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonService.Domain.Entities.Worker", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.PartnerAgency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommonService.Domain.Entities.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("KycReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CommonService.Domain.Entities.WorkerSkill", b =>
                {
                    b.HasOne("CommonService.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonService.Domain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
